import { buildMetadata } from '@/lib/seo';
export const metadata = buildMetadata({
  title: 'About Us | Steel Supply for Contractors',
  description: 'Learn about steel supply support for contractors, fabricators and MEP teams sourcing mild steel, stainless steel, galvanized steel and aluminium products.',
  path: '/about',
  keywords: ['steel supplier for contractors', 'steel supplier for fabricators', 'mild steel supplier', 'stainless steel supplier', 'galvanized steel supplier'],
  image: '/banners/products-banner.webp',
});
export default function AboutPage() { return <>
  <section className="page-hero"><div className="container"><p className="eyebrow">About SRK Steel</p><h1>Leading Suppliers, Since 1998</h1><p className="section-text">SRK Steel supports contractors, fabricators, fitout companies, MEP teams and procurement departments with practical steel product supply coordination.</p></div></section>
  <section className="section"><div className="container about-intro-grid"><div><p className="eyebrow">Who We Are</p><h2 className="large-title">Steel Supply Focused on Real Project Requirements</h2><p className="lead-copy">SRK Steel is a steel product supplier focused on construction, industrial, fabrication, roofing, cladding, interior fitout and MEP support requirements. The product range includes mild steel, stainless steel, galvanized steel and aluminium product groups including coils, sheets, panels, profiles, purlins, decking sheets, drywall systems, strut and track and GI pipes.</p><p className="lead-copy">Our approach is practical: understand the product requirement, check the key specification details and help buyers send an RFQ that includes the information needed for a useful response. This is especially important when drawings, BOQ notes, grade, size, finish and delivery location affect the final product choice.</p><p className="lead-copy">SRK Steel reviews enquiries from UAE and selected GCC and Middle East markets including Bahrain, Qatar, Kuwait, Saudi Arabia, Iraq, Oman and Jordan.</p></div><div className="stats about-stats"><div className="stat"><strong>25+</strong><span>Years</span></div><div className="stat"><strong>250+</strong><span>Products</span></div><div className="stat"><strong>10k+</strong><span>Projects</span></div><div className="stat"><strong>500+</strong><span>Customers</span></div></div></div></section>
  <section className="section soft"><div className="container visual-copy-grid"><div><p className="eyebrow">Company Strengths</p><h2 className="large-title">Why Buyers Work With SRK Steel</h2><p className="lead-copy">Buyers need more than a product name when steel is being ordered for a site. They need the right profile, grade, thickness, finish, quantity and delivery plan. SRK Steel pages are written to help teams check those details before they contact the team.</p><p className="lead-copy">The team can discuss product availability, material certificate requirements where applicable, cutting or punching needs, packing preferences and delivery location so the enquiry can be reviewed properly.</p></div><aside className="content-panel"><h3>Trust Signals</h3><ul className="copy-list"><li>Established steel trading experience since 1998.</li><li>Product pages with specification tables and common applications.</li><li>RFQ review based on drawings, BOQ notes and delivery location.</li><li>Material certificate discussion where project documents require it.</li><li>Country pages for UAE, Bahrain, Qatar, Kuwait, Saudi Arabia, Iraq, Oman and Jordan enquiries.</li></ul></aside></div></section>
</>; }
