export type Product = {
  slug: string;
  name: string;
  category: string;
  short: string;
  intro: string;
  image: string;
  specs: { label: string; value: string }[];
  applications: string[];
  features: string[];
};

export type CategoryInfo = {
  slug: string;
  name: string;
  description: string;
  image: string;
  heroImage?: string;
};

export type Country = {
  slug: string;
  name: string;
  cities: string;
  description: string;
  buyerFocus: string;
};

export type Application = {
  slug: string;
  title: string;
  description: string;
  image: string;
  recommendedProducts: string[];
  requirements: string[];
};

export const company = {
  name: 'SRK Steel',
  phone: '+971 58 660 0183',
  whatsapp: '+971 52 216 0874',
  email: 'sales@srksteel.com',
  secondaryEmail: 'Sales@srkmetals.com',
  rfqEmails: ['sales@srksteel.com', 'Sales@srkmetals.com'] as const,
  address: 'UAE and GCC project support',
  tagline: 'Industrial Excellence',
  salesPhoneLabel: 'Sales & Purchase Team',
  quickSupportLabel: 'Quick Support',
  googleBusinessUrl: 'https://share.google/sv1VdBFzYj2f51vs4',
};

export const categoryInfo: CategoryInfo[] = [
  {
    slug: 'mild-steel-products',
    name: 'Mild Steel Products',
    description: 'MS hollow sections, beams, channels, bars, angles, HR/CR coils, sheets, plates, gratings, MS decking sheets and shear studs for structural and fabrication requirements.',
    image: '/categories/mild-steel-products.jpg',
    heroImage: '/categories/mild-steel-products-hero-banner.jpg',
  },
  {
    slug: 'stainless-steel',
    name: 'Stainless Steel',
    description: 'SS coils, wire, plain sheets and slitted coils for fabrication, cladding, production and industrial requirements.',
    image: '/categories/stainless-steel.jpg',
    heroImage: '/categories/stainless-steel-hero-banner.jpg',
  },
  {
    slug: 'galvanized-steel',
    name: 'Galvanized Steel',
    description: 'GI coils, coated coils, sheets, insulated panels, corrugated profiles, decking sheets, purlins, drywall systems, strut tracks and GI pipes.',
    image: '/categories/galvanized-steel.jpg',
    heroImage: '/categories/galvanized-steel-hero-banner.jpg',
  },
  {
    slug: 'aluminium',
    name: 'Aluminium',
    description: 'Aluminium coils, plain sheets, pre-painted aluminium coils and PFMB/PSMR 3003-H14 coated coils for lightweight cladding, roofing accessories, panels and fabrication work.',
    image: '/categories/aluminium.jpg',
    heroImage: '/categories/aluminium-hero-banner.jpg',
  },
];

export const categories = categoryInfo.map((category) => category.name);
export const categoryBySlug = (slug: string) => categoryInfo.find((category) => category.slug === slug);

export const products: Product[] = [
  {
    slug: 'ms-hollow-sections',
    name: 'MS Hollow Sections',
    category: 'Mild Steel Products',
    short: 'Mild steel hollow sections for fabrication, structural frames, supports and general engineering work.',
    intro: 'MS hollow sections are used for frames, supports, gates, sheds, fabrication packages and general engineering work. Share section type, size, wall thickness, length and quantity for a clear RFQ.',
    image: '/products/ms-hollow-sections.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / MS' },
      { label: 'Supply', value: 'Square, rectangular and round hollow sections as required' },
      { label: 'Common use', value: 'Frames, supports, fabrication and industrial steel work' },
      { label: 'RFQ details', value: 'Section size, wall thickness, length, quantity and delivery location' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction', 'Industrial Warehouses'],
    features: ['Square/RHS options', 'Fabrication friendly', 'Structural support', 'Cut length options'],
  },
  {
    slug: 'ms-beams',
    name: 'MS Beams',
    category: 'Mild Steel Products',
    short: 'Mild steel beams for structural support, fabrication and industrial construction packages.',
    intro: 'MS beams are requested for structural frames, platforms, support members and industrial construction packages. Include beam type, size, length, grade and quantity with your RFQ.',
    image: '/products/ms-beams.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / structural steel' },
      { label: 'Supply', value: 'I beams, H beams and project-specified beam sections' },
      { label: 'Common use', value: 'Structural frames, supports, platforms and fabrication' },
      { label: 'RFQ details', value: 'Beam size, length, grade, quantity, cutting needs and project city' },
    ],
    applications: ['Industrial Warehouses', 'Commercial Construction', 'Fabrication Workshops'],
    features: ['Heavy support', 'BOQ friendly', 'Cutting support', 'Bulk supply'],
  },
  {
    slug: 'ms-channels',
    name: 'MS Channels',
    category: 'Mild Steel Products',
    short: 'Mild steel channels for bracing, support frames, fabrication and construction work.',
    intro: 'MS channels are used in support frames, bracing, platforms, industrial structures and fabrication. Confirm size, length, finish and quantity before sending the requirement.',
    image: '/products/ms-channels.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / MS' },
      { label: 'Supply', value: 'C channel / U channel as per project requirement' },
      { label: 'Common use', value: 'Support frames, platforms, bracing and fabrication' },
      { label: 'RFQ details', value: 'Channel size, length, thickness/weight, quantity and delivery location' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction', 'Industrial Warehouses'],
    features: ['Support profile', 'Bracing use', 'Fabrication friendly', 'Project quantities'],
  },
  {
    slug: 'ms-bars',
    name: 'MS Bars',
    category: 'Mild Steel Products',
    short: 'Mild steel bars for fabrication, machining, general engineering and construction use.',
    intro: 'MS bars are suitable for fabrication, machine components, supports, brackets and general engineering work. Send bar type, diameter or size, length, grade and quantity for review.',
    image: '/products/ms-bars.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / MS' },
      { label: 'Supply', value: 'Round bars, square bars and flat bars where available' },
      { label: 'Common use', value: 'Fabrication, supports, brackets and general engineering' },
      { label: 'RFQ details', value: 'Bar type, size, length, quantity and delivery city' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction'],
    features: ['Round/flat/square options', 'Cutting support', 'General engineering', 'Workshop use'],
  },
  {
    slug: 'ms-angles',
    name: 'MS Angles',
    category: 'Mild Steel Products',
    short: 'Mild steel angles for bracing, frames, supports, racks and fabrication work.',
    intro: 'MS angles are practical for frames, racks, bracing, edge supports and fabrication. Include angle size, thickness, length, quantity and finish requirement when requesting pricing.',
    image: '/products/ms-angles.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / MS' },
      { label: 'Supply', value: 'Equal or unequal angle as per requirement' },
      { label: 'Common use', value: 'Bracing, frames, support edges, racks and fabrication' },
      { label: 'RFQ details', value: 'Angle size, thickness, length, quantity and finish' },
    ],
    applications: ['Fabrication Workshops', 'Industrial Warehouses', 'Commercial Construction'],
    features: ['Bracing support', 'Easy fabrication', 'Project lengths', 'Cost-effective profile'],
  },
  {
    slug: 'hr-coils-ms',
    name: 'HR Coils - MS',
    category: 'Mild Steel Products',
    short: 'Hot rolled mild steel coils for processing, fabrication and sheet conversion requirements.',
    intro: 'HR coils are used for processing, fabrication and conversion where hot rolled mild steel is suitable. Share thickness, width, grade, coil weight or tonnage and delivery location.',
    image: '/products/hr-coils-ms.jpg',
    specs: [
      { label: 'Material', value: 'Hot rolled mild steel' },
      { label: 'Supply', value: 'Coil form, subject to thickness and width requirement' },
      { label: 'Common use', value: 'Processing, fabrication, cutting and forming applications' },
      { label: 'RFQ details', value: 'Thickness, width, grade, coil weight/tonnage and delivery city' },
    ],
    applications: ['Fabrication Workshops', 'Roofing & Cladding', 'Commercial Construction'],
    features: ['Bulk coil supply', 'Processing friendly', 'Thickness options', 'Cutting support'],
  },
  {
    slug: 'cr-coils-ms',
    name: 'CR Coils - MS',
    category: 'Mild Steel Products',
    short: 'Cold rolled mild steel coils for smoother finish, forming and precision sheet applications.',
    intro: 'CR coils are used where smoother surface quality, closer thickness control or forming support is needed. Include thickness, width, grade, surface requirement, quantity and delivery city.',
    image: '/products/cr-coils-ms.jpg',
    specs: [
      { label: 'Material', value: 'Cold rolled mild steel' },
      { label: 'Supply', value: 'CR coil, slit coil or cut-to-length where required' },
      { label: 'Common use', value: 'Forming, sheet processing, panels and fabrication' },
      { label: 'RFQ details', value: 'Thickness, width, surface requirement, quantity and delivery location' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction'],
    features: ['Smoother surface', 'Processing support', 'Slitting option', 'Fabrication use'],
  },
  {
    slug: 'ms-sheets',
    name: 'MS Sheets',
    category: 'Mild Steel Products',
    short: 'Mild steel sheets for fabrication, panels, general construction and industrial use.',
    intro: 'MS sheets are used for panels, covers, trays, enclosures, fabrication and general construction requirements. Send sheet thickness, size, grade, quantity and cutting details.',
    image: '/products/ms-sheets.jpg',
    specs: [
      { label: 'Material', value: 'Mild steel sheet' },
      { label: 'Supply', value: 'Standard sheets or cut-to-size support where required' },
      { label: 'Common use', value: 'Fabrication, panels, covers, trays and general steel work' },
      { label: 'RFQ details', value: 'Thickness, sheet size, grade, quantity and cutting needs' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction', 'Industrial Warehouses'],
    features: ['Sheet supply', 'Cut-to-size support', 'Fabrication use', 'General construction'],
  },
  {
    slug: 'ms-plates',
    name: 'MS Plates',
    category: 'Mild Steel Products',
    short: 'Mild steel plates for base plates, fabrication, structural parts and heavy-duty applications.',
    intro: 'MS plates are requested for base plates, brackets, structural parts, machine bases and heavy-duty fabrication. Confirm thickness, size, grade, cutting requirement and quantity.',
    image: '/products/ms-plates.jpg',
    specs: [
      { label: 'Material', value: 'Mild steel plate' },
      { label: 'Supply', value: 'Standard plates or cutting support depending on requirement' },
      { label: 'Common use', value: 'Base plates, brackets, fabrication and structural parts' },
      { label: 'RFQ details', value: 'Thickness, plate size, grade, cutting details, quantity and delivery city' },
    ],
    applications: ['Fabrication Workshops', 'Industrial Warehouses', 'Commercial Construction'],
    features: ['Heavy-duty use', 'Base plate work', 'Cutting support', 'Structural fabrication'],
  },
  {
    slug: 'mild-steel-gratings',
    name: 'Mild Steel Gratings',
    category: 'Mild Steel Products',
    short: 'MS gratings for walkways, platforms, drainage covers and industrial flooring areas.',
    intro: 'Mild steel gratings are used in industrial walkways, platforms, drainage covers, maintenance areas and open-grid flooring zones. Share grating size, load requirement, finish and quantity.',
    image: '/products/mild-steel-gratings.jpg',
    specs: [
      { label: 'Material', value: 'Mild steel grating' },
      { label: 'Supply', value: 'Panels by size, load and finish requirement' },
      { label: 'Common use', value: 'Platforms, walkways, drainage covers and industrial floors' },
      { label: 'RFQ details', value: 'Panel size, load requirement, finish, quantity and project location' },
    ],
    applications: ['Industrial Warehouses', 'Commercial Construction', 'Fabrication Workshops'],
    features: ['Walkway support', 'Drainage cover use', 'Load-based selection', 'Industrial flooring'],
  },
  {
    slug: 'decking-sheets-ms',
    name: 'Decking Sheets (MS)',
    category: 'Mild Steel Products',
    short: 'Mild steel decking sheets for composite flooring, mezzanine and slab support requirements.',
    intro: 'MS decking sheets are used where drawings call for mild steel deck profiles or related composite flooring components. Share profile type, thickness, length, quantity and drawing reference.',
    image: '/products/decking-sheets-ms.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / MS as per project requirement' },
      { label: 'Supply', value: 'Decking profile 45/150, 75/305 or drawing-based profile where applicable' },
      { label: 'Common use', value: 'Composite slab, mezzanine flooring and metal deck applications' },
      { label: 'RFQ details', value: 'Profile, thickness, length, quantity, shear stud details and delivery city' },
    ],
    applications: ['Commercial Construction', 'Industrial Warehouses'],
    features: ['Composite flooring', 'Drawing-based supply', 'Profile options', 'Shear stud coordination'],
  },
  {
    slug: 'ms-shear-studs',
    name: 'MS Shear Studs',
    category: 'Mild Steel Products',
    short: 'Mild steel shear studs for composite decking and structural slab connection requirements.',
    intro: 'MS shear studs are used with composite deck slab systems to support shear connection requirements. Send diameter, height, quantity, decking profile and drawing reference.',
    image: '/products/ms-shear-studs.jpg',
    specs: [
      { label: 'Material', value: 'Mild Steel / MS' },
      { label: 'Supply', value: 'Shear studs by project drawing and deck profile' },
      { label: 'Common use', value: 'Composite decking, slab connection and structural floor systems' },
      { label: 'RFQ details', value: 'Stud diameter, height, quantity, profile and drawing reference' },
    ],
    applications: ['Commercial Construction', 'Industrial Warehouses'],
    features: ['Decking support', 'Composite slab use', 'Project quantity supply', 'Drawing-based RFQ'],
  },
  {
    slug: 'ss-coil',
    name: 'SS Coil',
    category: 'Stainless Steel',
    short: 'Stainless steel coils for fabrication, processing, cladding and industrial production.',
    intro: 'SS coils are supplied by grade, thickness, width, finish and quantity for fabrication, cladding, processing and industrial supply requirements.',
    image: '/products/ss-coil.jpg',
    specs: [
      { label: 'Material', value: 'Stainless Steel - SS' },
      { label: 'Supply', value: 'Coils, slit coils or cut-to-length where required' },
      { label: 'Common use', value: 'Fabrication, cladding, processing and industrial production' },
      { label: 'RFQ details', value: 'Grade, thickness, width, finish, coil weight/tonnage and delivery location' },
    ],
    applications: ['Fabrication Workshops', 'Roofing & Cladding'],
    features: ['Grade options', 'Finish options', 'Slitting support', 'Certificate support'],
  },
  {
    slug: 'ss-wire',
    name: 'SS Wire',
    category: 'Stainless Steel',
    short: 'Stainless steel wire for fabrication, mesh, tying, forming and industrial applications.',
    intro: 'SS wire is requested for fabrication, mesh work, tying, forming and industrial applications where corrosion resistance and clean finish are important.',
    image: '/products/ss-wire.jpg',
    specs: [
      { label: 'Material', value: 'Stainless Steel - SS' },
      { label: 'Supply', value: 'Wire by diameter, grade and coil/spool requirement' },
      { label: 'Common use', value: 'Mesh, fabrication, tying, forming and industrial work' },
      { label: 'RFQ details', value: 'Wire diameter, grade, finish, coil/spool quantity and delivery location' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction'],
    features: ['Corrosion resistance', 'Diameter options', 'Coil/spool supply', 'Industrial use'],
  },
  {
    slug: 'ss-plain-sheet',
    name: 'SS Plain Sheet',
    category: 'Stainless Steel',
    short: 'Stainless steel plain sheets for fabrication, cladding, panels and interior/exterior finishing.',
    intro: 'SS plain sheets are used for panels, cladding, fabrication, kitchen/industrial work and architectural finishing. Confirm grade, thickness, finish and sheet size before RFQ.',
    image: '/products/ss-plain-sheet.jpg',
    specs: [
      { label: 'Material', value: 'Stainless Steel - SS' },
      { label: 'Supply', value: 'Plain sheets in standard or cut sizes where available' },
      { label: 'Common use', value: 'Fabrication, panels, cladding and finishing work' },
      { label: 'RFQ details', value: 'Grade, thickness, finish, sheet size, quantity and cutting needs' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction', 'Interior Fitout'],
    features: ['Clean finish', 'Grade options', 'Cutting support', 'Cladding use'],
  },
  {
    slug: 'ss-slitted-coil',
    name: 'SS Slitted Coil',
    category: 'Stainless Steel',
    short: 'Stainless steel slitted coils for strip processing, fabrication and production requirements.',
    intro: 'SS slitted coils are used when narrow strip widths are required for fabrication, forming, profiles and production work. Share grade, parent thickness, slit width and quantity.',
    image: '/products/ss-slitted-coil.jpg',
    specs: [
      { label: 'Material', value: 'Stainless Steel - SS' },
      { label: 'Supply', value: 'Slitted coil / narrow strip supply' },
      { label: 'Common use', value: 'Strip processing, forming, fabrication and production' },
      { label: 'RFQ details', value: 'Grade, thickness, slit width, finish, quantity and packing requirement' },
    ],
    applications: ['Fabrication Workshops', 'Roofing & Cladding'],
    features: ['Custom slit width', 'Processing support', 'Grade options', 'Bulk supply'],
  },
  {
    slug: 'gi-coil',
    name: 'GI Coil',
    category: 'Galvanized Steel',
    short: 'Hot-dip galvanized steel coils and sheets supplied to project-specific grade, thickness, width, zinc-coating, surface-finish and documentation requirements.',
    intro: 'SRK Steel supplies Hot-Dip Galvanized Steel Coils (GI Coils) and Galvanized Steel Sheets manufactured in accordance with leading ASTM, JIS and EN specifications. Material can be supplied with agreed mechanical, dimensional and zinc-coating requirements for industrial, construction and fabrication applications.',
    image: '/products/gi-coil.jpg',
    specs: [
      { label: 'Material', value: 'Galvanized Steel / Hot-Dip Galvanized Steel' },
      { label: 'Supply & processing', value: 'Galvanized coil supply, cut-to-length and slitting subject to the required specification' },
      { label: 'Typical thickness range', value: '0.20–2.50 mm coil/slitting; 0.20–5.00 mm cut-to-length, as specified' },
      { label: 'Typical width range', value: 'Up to 1,219 mm coil; up to 2,000 mm cut-to-length; slit widths from 50 mm, as specified' },
      { label: 'Zinc coating', value: '60–275 g/m² in the documented supply range' },
      { label: 'Standards referenced', value: 'ASTM A653/A653M, EN 10346 and JIS G 3302' },
      { label: 'RFQ details', value: 'Grade, thickness, width, coating designation, finish/treatment, quantity, packing, MTC/documentation and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Fabrication Workshops'],
    features: ['ASTM / EN / JIS options', '60–275 g/m² coating range', 'Cut-to-length & slitting support', 'MTC / documentation support'],
  },
  {
    slug: 'ppgi-coil',
    name: 'PPGI Coil',
    category: 'Galvanized Steel',
    short: 'Pre-Painted Galvanized Steel coils and sheets supplied for roofing, cladding, panels, fabrication and colour-coated applications with project-specific coating and paint requirements.',
    intro: 'SRK Steel supplies PPGI coils and sheets manufactured and tested according to applicable international standards and customer specifications. Quality inspection can include mechanical, dimensional, metallic-coating and paint-performance testing according to the required application.',
    image: '/products/ppgi-coil.jpg',
    specs: [
      { label: 'Material', value: 'Pre-Painted Galvanized Steel - PPGI' },
      { label: 'Substrate', value: 'Galvanized substrate; other prepainted substrate references are documented in the detailed technical section' },
      { label: 'Typical thickness range', value: '0.25–1.20 mm in the documented application table' },
      { label: 'Typical width range', value: '100–1,350 mm depending on application in the documented table' },
      { label: 'Coating / paint systems', value: 'RMP and PVDF references, with primer, top-coat and back-coat requirements by specification' },
      { label: 'Colour', value: 'RAL colour references and project-specific colour requirements' },
      { label: 'RFQ details', value: 'Substrate, thickness, width, metallic coating, paint system, colour/RAL, quantity, testing/documentation and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Colour-coated steel', 'Paint-performance testing', 'RAL colour options', 'Roofing & panel applications'],
  },
  {
    slug: 'aluzinc-coil',
    name: 'Aluzinc Coil',
    category: 'Galvanized Steel',
    short: 'Aluzinc coils and sheets, also known as Galvalume steel, supplied for roofing, cladding, PEB, HVAC, panels and industrial fabrication applications.',
    intro: 'SRK Steel supplies Aluzinc steel coils, cut-to-length sheets and slit coils in different thicknesses, widths, coating masses, steel grades, surface finishes and treatment options according to project and customer requirements.',
    image: '/products/aluzinc-coil.jpg',
    specs: [
      { label: 'Material', value: '55% aluminum-zinc alloy-coated steel / Aluzinc / Galvalume' },
      { label: 'Supply forms', value: 'Coils, cut-to-length sheets and slit coils' },
      { label: 'Typical coil thickness', value: '0.12–3.80 mm*' },
      { label: 'Typical coil width', value: '650–1,350 mm*' },
      { label: 'Coating mass references', value: 'AZ30, AZ50, AZ70, AZ100, AZ120 and AZ150, subject to applicable specification' },
      { label: 'Standards referenced', value: 'ASTM A792/A792M, EN 10346 and JIS G 3321' },
      { label: 'RFQ details', value: 'Grade, thickness, width, AZ coating, surface finish/treatment, coil or sheet requirement, quantity, MTC/documentation and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Al-Zn coated steel', 'Coil / sheet / slit supply', 'ASTM / EN / JIS references', 'Quality documentation support'],
  },
  {
    slug: 'pvdf-coils',
    name: 'PVDF Coils',
    category: 'Galvanized Steel',
    short: 'PVDF coated steel coils for premium façade, roofing and cladding applications.',
    intro: 'PVDF coils are used where durable colour coating, exterior performance and architectural finish are required. Share colour, coating system, thickness and project quantity.',
    image: '/products/pvdf-coils.jpg',
    specs: [
      { label: 'Material', value: 'PVDF coated steel' },
      { label: 'Supply', value: 'Colour-coated coil by project shade and coating specification' },
      { label: 'Common use', value: 'Façade, roofing, cladding and architectural panels' },
      { label: 'RFQ details', value: 'PVDF coating, colour, thickness, width, quantity and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Premium coating', 'Exterior finish', 'Colour options', 'Façade use'],
  },
  {
    slug: 'gi-plain-sheet',
    name: 'GI Plain Sheet',
    category: 'Galvanized Steel',
    short: 'Galvanized plain sheets for fabrication, panels, ducting, cladding and general steel work.',
    intro: 'GI plain sheets are practical for ducting, panels, fabrication, covers and general steel work where a galvanized finish is required.',
    image: '/products/gi-plain-sheet.jpg',
    specs: [
      { label: 'Material', value: 'Galvanized Steel - GI' },
      { label: 'Supply', value: 'Plain sheets in standard or cut sizes where available' },
      { label: 'Common use', value: 'Fabrication, panels, ducting, cladding and general use' },
      { label: 'RFQ details', value: 'Thickness, sheet size, coating, quantity and cutting needs' },
    ],
    applications: ['Fabrication Workshops', 'Commercial Construction', 'MEP & Support Systems'],
    features: ['Galvanized finish', 'Sheet supply', 'Cutting support', 'General fabrication'],
  },
  {
    slug: 'gi-slitted-coils',
    name: 'GI Slitted Coils',
    category: 'Galvanized Steel',
    short: 'Galvanized slitted coils for strip production, profiles and fabrication use.',
    intro: 'GI slitted coils are supplied for strip processing, profile making, components and fabrication where a narrower coil width is required.',
    image: '/products/gi-slitted-coils.jpg',
    specs: [
      { label: 'Material', value: 'Galvanized Steel - GI' },
      { label: 'Supply', value: 'Slitted coil / narrow strip supply' },
      { label: 'Common use', value: 'Strip production, profiles, components and fabrication' },
      { label: 'RFQ details', value: 'Thickness, slit width, coating GSM, quantity and packing requirement' },
    ],
    applications: ['Fabrication Workshops', 'Roofing & Cladding'],
    features: ['Slit widths', 'GI coating', 'Profile production', 'Processing use'],
  },
  {
    slug: 'ppgi-slitted-coils',
    name: 'PPGI Slitted Coils',
    category: 'Galvanized Steel',
    short: 'Pre-painted galvanized slitted coils for colour-coated strips, flashings and profile production.',
    intro: 'PPGI slitted coils are used when colour-coated steel strip is needed for flashings, profiles, edge trims and production work.',
    image: '/products/ppgi-slitted-coils.jpg',
    specs: [
      { label: 'Material', value: 'Pre-painted Galvanized Steel - PPGI' },
      { label: 'Supply', value: 'Colour-coated slit coils by width requirement' },
      { label: 'Common use', value: 'Flashings, trims, profiles and production work' },
      { label: 'RFQ details', value: 'Colour/RAL, coating, slit width, thickness and quantity' },
    ],
    applications: ['Roofing & Cladding', 'Fabrication Workshops'],
    features: ['Colour-coated strips', 'Slitting support', 'Profile use', 'Finish options'],
  },
  {
    slug: 'ppgi-plain-sheet',
    name: 'PPGI Plain Sheet',
    category: 'Galvanized Steel',
    short: 'Pre-painted galvanized plain sheets for roofing accessories, panels, cladding and fabrication.',
    intro: 'PPGI plain sheets are selected when a flat colour-coated sheet is required for panels, cladding accessories, flashings and fabrication.',
    image: '/products/ppgi-plain-sheet.jpg',
    specs: [
      { label: 'Material', value: 'Pre-painted Galvanized Steel - PPGI' },
      { label: 'Supply', value: 'Plain colour-coated sheets by size and finish' },
      { label: 'Common use', value: 'Panels, roofing accessories, cladding and fabrication' },
      { label: 'RFQ details', value: 'Colour/RAL, thickness, sheet size, coating and quantity' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Colour-coated sheets', 'Panel use', 'Cutting support', 'Exterior finish'],
  },
  {
    slug: 'roof-insulated-panels',
    name: 'Roof Insulated Panels - GI/PPGI',
    category: 'Galvanized Steel',
    short: 'GI/PPGI roof insulated panels for industrial roofing, warehouses and controlled interior areas.',
    intro: 'Roof insulated panels combine coated steel skins with insulation for roofing systems that require faster installation and thermal performance.',
    image: '/products/roof-insulated-panels.jpg',
    specs: [
      { label: 'Material', value: 'GI/PPGI outer sheets with insulation core' },
      { label: 'Supply', value: 'Roof panels by thickness, skin finish and project length' },
      { label: 'Common use', value: 'Industrial roofing, warehouses and insulated roof systems' },
      { label: 'RFQ details', value: 'Panel thickness, skin material, colour, length, quantity and delivery city' },
    ],
    applications: ['Industrial Warehouses', 'Roofing & Cladding'],
    features: ['Thermal insulation', 'Roof panel system', 'Colour options', 'Project lengths'],
  },
  {
    slug: 'wall-insulated-panels',
    name: 'Wall Insulated Panels',
    category: 'Galvanized Steel',
    short: 'Insulated wall panels for industrial buildings, warehouses, partitions and exterior wall systems.',
    intro: 'Wall insulated panels are used for building envelopes, partitions and wall systems where insulation and clean panel installation are required.',
    image: '/products/wall-insulated-panels.jpg',
    specs: [
      { label: 'Material', value: 'GI/PPGI steel skins with insulation core' },
      { label: 'Supply', value: 'Wall panels by thickness, finish and length' },
      { label: 'Common use', value: 'Industrial walls, partitions, warehouses and envelope systems' },
      { label: 'RFQ details', value: 'Panel thickness, skin finish, colour, length, quantity and delivery location' },
    ],
    applications: ['Industrial Warehouses', 'Commercial Construction', 'Interior Fitout'],
    features: ['Insulated wall system', 'Fast installation', 'Clean finish', 'Project lengths'],
  },
  {
    slug: 'corrugated-roofing-sheet',
    name: 'Corrugated Roofing Sheet',
    category: 'Galvanized Steel',
    short: 'Corrugated galvanized or colour-coated roofing sheets for industrial and commercial roofing.',
    intro: 'Corrugated roofing sheets are used for sheds, warehouses, industrial roofs and general roof covering where profile, coating and length are specified by project.',
    image: '/products/corrugated-roofing-sheet.jpg',
    specs: [
      { label: 'Material', value: 'GI / PPGI / coated steel' },
      { label: 'Supply', value: 'Corrugated sheets by profile, coating and length' },
      { label: 'Common use', value: 'Industrial roofing, sheds, warehouses and commercial roofs' },
      { label: 'RFQ details', value: 'Profile, thickness, coating, colour, length, quantity and delivery city' },
    ],
    applications: ['Roofing & Cladding', 'Industrial Warehouses'],
    features: ['Roof profile', 'Custom lengths', 'Coating options', 'Fast installation'],
  },
  {
    slug: 'corrugated-wall-sheet',
    name: 'Corrugated Wall Sheet',
    category: 'Galvanized Steel',
    short: 'Corrugated wall sheets for cladding, partitions and exterior wall covering.',
    intro: 'Corrugated wall sheets are used for exterior cladding, partitions and wall covering where a profiled steel finish is required.',
    image: '/products/corrugated-wall-sheet.jpg',
    specs: [
      { label: 'Material', value: 'GI / PPGI / coated steel' },
      { label: 'Supply', value: 'Corrugated wall sheets by profile and finish' },
      { label: 'Common use', value: 'Wall cladding, partitions and exterior covering' },
      { label: 'RFQ details', value: 'Profile, thickness, coating, colour, length and quantity' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Wall cladding', 'Profile options', 'Colour-coated option', 'Project lengths'],
  },
  {
    slug: 'corrugated-fence-sheet-panel',
    name: 'Corrugated Fence Sheet / Panel',
    category: 'Galvanized Steel',
    short: 'Corrugated fence sheets and panels for site fencing, boundary panels and temporary works.',
    intro: 'Corrugated fence sheets are used for site fencing, boundary panels, enclosures and temporary works where durable steel sheet covering is required.',
    image: '/products/corrugated-fence-sheet-panel.jpg',
    specs: [
      { label: 'Material', value: 'GI / PPGI / coated steel' },
      { label: 'Supply', value: 'Fence sheets or panels by height, length and colour' },
      { label: 'Common use', value: 'Site fencing, boundaries, temporary enclosures and panels' },
      { label: 'RFQ details', value: 'Sheet height, profile, thickness, colour, quantity and delivery location' },
    ],
    applications: ['Commercial Construction', 'Industrial Warehouses'],
    features: ['Fence panel use', 'Colour options', 'Durable sheet', 'Site works'],
  },
  {
    slug: 'corrugated-curve',
    name: 'Corrugated Curve',
    category: 'Galvanized Steel',
    short: 'Curved corrugated sheets for special roofing, canopy and architectural profile requirements.',
    intro: 'Corrugated curved sheets are required for curved roof sections, canopies and special profile applications where radius and profile must match drawings.',
    image: '/products/corrugated-curve.jpg',
    specs: [
      { label: 'Material', value: 'GI / PPGI / coated steel' },
      { label: 'Supply', value: 'Curved corrugated sheets by radius and profile' },
      { label: 'Common use', value: 'Curved roofing, canopies and special cladding details' },
      { label: 'RFQ details', value: 'Profile, radius, thickness, colour, quantity and drawing reference' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Curved profile', 'Drawing-based supply', 'Roofing use', 'Custom requirement'],
  },
  {
    slug: 'corrugated-ridge',
    name: 'Corrugated Ridge',
    category: 'Galvanized Steel',
    short: 'Corrugated ridge pieces for roofing sheet junctions, ridges and finishing details.',
    intro: 'Corrugated ridge pieces are used at roof peaks and junctions to complete profiled roofing systems and improve weather protection at sheet intersections.',
    image: '/products/corrugated-ridge.jpg',
    specs: [
      { label: 'Material', value: 'GI / PPGI / coated steel' },
      { label: 'Supply', value: 'Ridge pieces by profile, angle and colour' },
      { label: 'Common use', value: 'Roof ridge finishing, sheet junctions and roofing accessories' },
      { label: 'RFQ details', value: 'Profile match, angle, colour, length, quantity and roof drawing' },
    ],
    applications: ['Roofing & Cladding'],
    features: ['Roof accessory', 'Profile matching', 'Colour options', 'Weather finishing'],
  },
  {
    slug: 'gutter-and-flashing',
    name: 'Gutter and Flashing',
    category: 'Galvanized Steel',
    short: 'Gutters and flashings for roofing edges, drainage lines and sheet metal finishing details.',
    intro: 'Gutters and flashings are sheet metal accessories used to manage roof edges, drainage, corners and junctions in roofing and cladding packages.',
    image: '/products/gutter-and-flashing.jpg',
    specs: [
      { label: 'Material', value: 'GI / PPGI / aluminium or coated steel as required' },
      { label: 'Supply', value: 'Custom formed gutters and flashings by drawing' },
      { label: 'Common use', value: 'Roof drainage, edge protection, junctions and cladding details' },
      { label: 'RFQ details', value: 'Profile drawing, thickness, colour, length, quantity and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Custom folding', 'Roof accessory', 'Colour matching', 'Drainage support'],
  },
  {
    slug: 'gi-decking-sheet',
    name: 'GI Decking Sheet - 45/150 and 75/305',
    category: 'Galvanized Steel',
    short: 'GI decking sheets in 45/150 and 75/305 profiles for composite slab and floor decking.',
    intro: 'GI decking sheets are used in composite flooring, mezzanine slabs and structural deck applications. Common profile references include 45/150 and 75/305 where specified.',
    image: '/products/gi-decking-sheet.jpg',
    specs: [
      { label: 'Material', value: 'Galvanized Steel - GI' },
      { label: 'Supply', value: 'Decking profiles 45/150 and 75/305 where applicable' },
      { label: 'Common use', value: 'Composite slab, mezzanine and flooring systems' },
      { label: 'RFQ details', value: 'Profile, thickness, length, quantity, drawing and shear stud requirement' },
    ],
    applications: ['Commercial Construction', 'Industrial Warehouses'],
    features: ['Composite deck', 'Profile options', 'Project lengths', 'Shear stud coordination'],
  },
  {
    slug: 'shear-studs',
    name: 'Shear Studs',
    category: 'Galvanized Steel',
    short: 'Shear studs for composite floor decking and structural slab connection systems.',
    intro: 'Shear studs are coordinated with metal decking systems where drawings require shear connection between steel beams and composite slabs.',
    image: '/products/shear-studs.jpg',
    specs: [
      { label: 'Material', value: 'Steel shear studs as per project requirement' },
      { label: 'Supply', value: 'Studs by diameter, height and quantity' },
      { label: 'Common use', value: 'Composite decking, slab connection and structural floor systems' },
      { label: 'RFQ details', value: 'Stud diameter, height, quantity, deck profile and drawing reference' },
    ],
    applications: ['Commercial Construction', 'Industrial Warehouses'],
    features: ['Composite slab support', 'Drawing-based RFQ', 'Decking accessory', 'Bulk supply'],
  },
  {
    slug: 'c-purlins',
    name: 'C Purlins',
    category: 'Galvanized Steel',
    short: 'Cold formed C purlins for roofing, wall girts and secondary steel framing.',
    intro: 'C purlins are supplied for warehouses, sheds, roofing, cladding and secondary framing. Share section size, thickness, length and punching schedule for RFQ review.',
    image: '/products/c-purlins.jpg',
    specs: [
      { label: 'Material', value: 'GI or black steel as per project requirement' },
      { label: 'Supply', value: 'Cut-to-length purlins with optional pre-punched holes' },
      { label: 'Common use', value: 'Roof framing, wall girts, sheds and industrial structures' },
      { label: 'RFQ details', value: 'Section size, thickness, length, quantity and delivery location' },
    ],
    applications: ['Industrial Warehouses', 'Roofing & Cladding', 'Commercial Construction'],
    features: ['Custom lengths', 'Hole punching', 'Roof support', 'Secondary framing'],
  },
  {
    slug: 'z-purlins',
    name: 'Z Purlins',
    category: 'Galvanized Steel',
    short: 'Z section purlins for roofing and cladding support in steel buildings.',
    intro: 'Z purlins support roof sheets and wall cladding in steel structures and are suitable for overlapping spans and long industrial roofing systems.',
    image: '/products/z-purlins.jpg',
    specs: [
      { label: 'Material', value: 'GI or black steel as per project requirement' },
      { label: 'Supply', value: 'Z section cold-formed steel purlin' },
      { label: 'Common use', value: 'Roofing, cladding and wall support systems' },
      { label: 'RFQ details', value: 'Section size, thickness, length, punching details and quantity' },
    ],
    applications: ['Industrial Warehouses', 'Roofing & Cladding'],
    features: ['Overlap friendly', 'Lightweight profile', 'Custom punching', 'Structural support'],
  },
  {
    slug: 'drywall-partition-systems',
    name: 'Dry Wall Partition Systems',
    category: 'Galvanized Steel',
    short: 'Galvanized studs, tracks and channels for drywall partitions and ceiling framing.',
    intro: 'Dry wall partition systems include GI studs, tracks, channels and accessories for fitout contractors, interior partitions and ceiling frameworks.',
    image: '/products/drywall-partition-systems.jpg',
    specs: [
      { label: 'Material', value: 'Galvanized Steel - GI' },
      { label: 'Supply', value: 'Studs, tracks, channels, furring and accessories' },
      { label: 'Common use', value: 'Partitions, ceilings and interior framing' },
      { label: 'RFQ details', value: 'Gauge, profile, quantity, accessories and project location' },
    ],
    applications: ['Interior Fitout', 'Commercial Construction'],
    features: ['Lightweight framing', 'Fitout use', 'Accessory bundle', 'Fast installation'],
  },
  {
    slug: 'strut-track',
    name: 'Strut & Track',
    category: 'Galvanized Steel',
    short: 'Strut channels and track systems for MEP, HVAC, cable tray and pipe support work.',
    intro: 'Strut and track systems provide modular support for MEP, HVAC, electrical, cable tray and pipe support installations.',
    image: '/products/strut-track.jpg',
    specs: [
      { label: 'Material', value: 'Pre-galvanized or hot dip galvanized steel' },
      { label: 'Supply', value: 'Plain/slotted strut, track and accessories' },
      { label: 'Common use', value: 'MEP support, cable trays, pipe supports and frames' },
      { label: 'RFQ details', value: 'Channel size, finish, length, accessory list and quantity' },
    ],
    applications: ['MEP & Support Systems', 'Industrial Warehouses'],
    features: ['MEP support', 'Accessory compatible', 'Modular install', 'Project lengths'],
  },
  {
    slug: 'gi-pipe',
    name: 'GI Pipe',
    category: 'Galvanized Steel',
    short: 'Galvanized pipes for support, fabrication, fencing, frames and industrial applications.',
    intro: 'GI pipes are used in support frames, fabrication, fencing, light structures and general industrial applications where galvanized coating is required.',
    image: '/products/gi-pipe.jpg',
    specs: [
      { label: 'Material', value: 'Galvanized Steel - GI' },
      { label: 'Supply', value: 'Pipe by diameter, wall thickness and length' },
      { label: 'Common use', value: 'Support frames, fencing, fabrication and industrial work' },
      { label: 'RFQ details', value: 'Diameter, wall thickness, length, finish, quantity and delivery city' },
    ],
    applications: ['Fabrication Workshops', 'MEP & Support Systems', 'Commercial Construction'],
    features: ['Galvanized coating', 'Pipe sizes', 'Fabrication use', 'Support frames'],
  },
  {
    slug: 'aluminium-coil',
    name: 'Aluminium Coil',
    category: 'Aluminium',
    short: 'Aluminium coils for roofing, cladding, fabrication and light industrial applications.',
    intro: 'Aluminium coils are used for roofing accessories, cladding, fabrication, insulation jacketing and applications where lightweight corrosion resistance is useful.',
    image: '/products/aluminium-coil.jpg',
    specs: [
      { label: 'Material', value: 'Aluminium - AL' },
      { label: 'Supply', value: 'Coil form by alloy, thickness and width requirement' },
      { label: 'Common use', value: 'Cladding, roofing accessories, fabrication and light industrial use' },
      { label: 'RFQ details', value: 'Alloy, thickness, width, finish, quantity and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Fabrication Workshops'],
    features: ['Lightweight', 'Corrosion resistant', 'Coil supply', 'Fabrication use'],
  },
  {
    slug: 'aluminium-plain-sheet',
    name: 'Aluminium Plain Sheet',
    category: 'Aluminium',
    short: 'Aluminium plain sheets for panels, cladding, fabrication and lightweight covering work.',
    intro: 'Aluminium plain sheets are selected for panels, covers, cladding, insulation works and fabrication where lighter weight is preferred.',
    image: '/products/aluminium-plain-sheet.jpg',
    specs: [
      { label: 'Material', value: 'Aluminium - AL' },
      { label: 'Supply', value: 'Plain sheets by size, thickness and alloy requirement' },
      { label: 'Common use', value: 'Panels, covers, cladding and fabrication' },
      { label: 'RFQ details', value: 'Alloy, thickness, sheet size, finish, quantity and cutting needs' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction', 'Fabrication Workshops'],
    features: ['Lightweight sheet', 'Cutting support', 'Cladding use', 'Corrosion resistant'],
  },
  {
    slug: 'pre-painted-aluminium-coils',
    name: 'Pre-painted Aluminium Coils',
    category: 'Aluminium',
    short: 'Prepainted Aluminium Coils (PPAL) for roofing, cladding, sandwich panels, ACP, ceilings, gutters and architectural or industrial applications.',
    intro: 'PPAL combines the lightweight and corrosion-resistant properties of aluminium with a durable factory-applied paint finish. SRK Steel supplies colour-coated aluminium coil requirements by alloy, temper, thickness, width, coating system and colour specification.',
    image: '/products/pre-painted-aluminium-coils.jpg',
    specs: [
      { label: 'Material', value: 'Prepainted Aluminium / PPAL' },
      { label: 'Standards referenced', value: 'ASTM B209 / EN / International Standards' },
      { label: 'Alloy references', value: '1100, 3003, 3004, 3005, 3105, 5005, 5052 and others' },
      { label: 'Temper references', value: 'H14, H16, H24, H26, H46, H48 and as required' },
      { label: 'Thickness', value: '0.20–1.20 mm' },
      { label: 'Width', value: 'Up to 1,350 mm' },
      { label: 'Coating systems', value: 'PE, SMP, PVDF, Epoxy and other systems' },
      { label: 'Colours', value: 'RAL and customised colours' },
      { label: 'RFQ details', value: 'Alloy, temper, thickness, width, coating system, colour/RAL, quantity, testing requirements and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction'],
    features: ['Factory-applied colour coating', 'Multiple alloy & temper references', 'PVDF / HDP / PUPA / SMP comparison', 'Quality testing reference'],
  },
  {
    slug: 'pfmb-psmr-aluminium-alloy-3003-h14-coils',
    name: 'PFMB/PSMR Aluminium Alloy 3003-H14 Coils',
    category: 'Aluminium',
    short: 'Aluminium alloy 3003-H14 coils with PSMR 75 micron coating for coated sheet, cladding and fabrication requirements.',
    intro: 'PFMB/PSMR aluminium alloy 3003-H14 coils are used where a coated aluminium coil is required for cladding, roofing accessories, panels and fabrication work. Share alloy, coating system, micron requirement, thickness, width, colour and quantity for RFQ review.',
    image: '/products/pfmb-psmr-aluminium-alloy-3003-h14-coils.jpg',
    specs: [
      { label: 'Material', value: 'Aluminium alloy 3003-H14' },
      { label: 'Coating', value: 'PSMR coating, 75 micron as specified' },
      { label: 'Common use', value: 'Cladding, roofing accessories, panels, fabrication and coated coil applications' },
      { label: 'RFQ details', value: 'Alloy, coating type, micron, thickness, width, colour, coil weight and delivery location' },
    ],
    applications: ['Roofing & Cladding', 'Commercial Construction', 'Fabrication Workshops'],
    features: ['3003-H14 alloy', 'PSMR 75 micron coating', 'Colour coated coil', 'Cladding and panel use'],
  },

];

export const countries: Country[] = [
  { slug: 'uae', name: 'UAE', cities: 'Dubai, Abu Dhabi, Sharjah and other Emirates', description: 'Steel products for UAE contractors, fabricators, fitout teams and MEP projects.', buyerFocus: 'UAE enquiries often need quick size confirmation, material certificates where required, and clear delivery coordination for active sites.' },
  { slug: 'bahrain', name: 'Bahrain', cities: 'Manama, Riffa, Sitra and industrial project areas', description: 'Steel product enquiries for Bahrain construction, fitout, MEP and fabrication requirements.', buyerFocus: 'Bahrain buyers usually need product availability, grade confirmation, packing details and delivery scope before confirming an order.' },
  { slug: 'qatar', name: 'Qatar', cities: 'Doha, Al Rayyan, Lusail and project zones', description: 'Steel product guidance for Qatar construction, MEP, fitout and infrastructure-related enquiries.', buyerFocus: 'Qatar contractors often compare galvanized profiles, stainless steel material, MEP support channels and certificate requirements before sending a purchase request.' },
  { slug: 'kuwait', name: 'Kuwait', cities: 'Kuwait City, Shuwaikh, Ahmadi and surrounding project areas', description: 'Steel products for Kuwait industrial, commercial, fabrication and maintenance projects.', buyerFocus: 'Kuwait RFQs normally require grade, thickness, quantity, finish and delivery city confirmation at the first stage.' },
  { slug: 'saudi-arabia', name: 'Saudi Arabia', cities: 'Riyadh, Jeddah, Dammam and Eastern Province', description: 'Steel product enquiries for Saudi Arabia construction, industrial, fabrication and infrastructure projects.', buyerFocus: 'Saudi Arabia projects may involve larger quantities, phased delivery planning, drawing review and acceptable product alternatives.' },
  { slug: 'iraq', name: 'Iraq', cities: 'Baghdad, Basra, Erbil and major project locations', description: 'Steel product enquiries for Iraq construction, industrial, oil and gas support and fabrication work.', buyerFocus: 'Iraq procurement teams often need product sizes, packing details, quantity breakdown and delivery coordination reviewed together.' },
  { slug: 'oman', name: 'Oman', cities: 'Muscat, Sohar, Salalah and industrial zones', description: 'Steel product enquiries for Oman roofing, cladding, MEP, marine-adjacent and fabrication projects.', buyerFocus: 'Oman buyers often need finish, exposure condition, grade and delivery city confirmed before final procurement.' },
  { slug: 'jordan', name: 'Jordan', cities: 'Amman, Zarqa, Aqaba and project locations', description: 'Steel product enquiries for Jordan contractors, fabricators, fitout teams and MEP buyers.', buyerFocus: 'Jordan buyers usually need product matching by grade, size, finish, quantity and delivery location before confirmation.' },
];

export const applications: Application[] = [
  { slug: 'industrial-warehouses', title: 'Industrial Warehouses', image: '/applications/industrial-warehouses.jpg', description: 'Decking sheets, purlins, roofing profiles, beams, channels and support systems for warehouses and sheds.', recommendedProducts: ['c-purlins', 'z-purlins', 'gi-decking-sheet', 'decking-sheets-ms', 'roof-insulated-panels', 'ms-beams', 'ms-channels', 'strut-track'], requirements: ['building span', 'roofing system', 'purlin spacing', 'deck profile', 'delivery location'] },
  { slug: 'commercial-construction', title: 'Commercial Construction', image: '/applications/commercial-construction.jpg', description: 'Steel sheets, decking sheets, stainless steel materials, partition systems and coated products for commercial projects.', recommendedProducts: ['gi-decking-sheet', 'decking-sheets-ms', 'drywall-partition-systems', 'ss-plain-sheet', 'gi-plain-sheet', 'aluminium-plain-sheet', 'pfmb-psmr-aluminium-alloy-3003-h14-coils', 'ms-beams'], requirements: ['drawings', 'floor system', 'fitout scope', 'grade and finish', 'quantity'] },
  { slug: 'interior-fitout', title: 'Interior Fitout', image: '/applications/interior-fitout.jpg', description: 'Drywall studs, tracks, stainless sheets, aluminium sheets and finishing materials for interior works.', recommendedProducts: ['drywall-partition-systems', 'strut-track', 'ss-plain-sheet', 'aluminium-plain-sheet', 'gi-plain-sheet'], requirements: ['partition height', 'gauge', 'profile type', 'accessories', 'project location'] },
  { slug: 'mep-support-systems', title: 'MEP & Support Systems', image: '/applications/mep-support-systems.jpg', description: 'Strut tracks, GI pipes, support channels and related steel products for mechanical and electrical teams.', recommendedProducts: ['strut-track', 'gi-pipe', 'ss-wire', 'ms-bars'], requirements: ['load requirement', 'channel size', 'finish', 'accessory list', 'installation environment'] },
  { slug: 'roofing-cladding', title: 'Roofing & Cladding', image: '/applications/roofing-cladding.jpg', description: 'Coated coils, corrugated sheets, purlins, flashings, gutters and insulated panels for roof and wall systems.', recommendedProducts: ['c-purlins', 'z-purlins', 'gi-coil', 'ppgi-coil', 'corrugated-roofing-sheet', 'corrugated-wall-sheet', 'gutter-and-flashing', 'roof-insulated-panels', 'pfmb-psmr-aluminium-alloy-3003-h14-coils'], requirements: ['roof span', 'sheet profile', 'coating', 'lengths', 'wind/load requirement'] },
  { slug: 'fabrication-workshops', title: 'Fabrication Workshops', image: '/applications/fabrication-workshops.jpg', description: 'Mild steel, stainless steel, galvanized and aluminium sheets/coils for fabrication and processing.', recommendedProducts: ['ms-hollow-sections', 'ms-plates', 'ms-angles', 'ss-coil', 'ss-plain-sheet', 'gi-plain-sheet', 'aluminium-coil', 'pfmb-psmr-aluminium-alloy-3003-h14-coils'], requirements: ['grade', 'size', 'wall thickness', 'finish', 'cutting/slitting requirement'] },
];

export const services = [
  'RFQ and BOQ review',
  'Cut-to-length supply support',
  'Material certificate support',
  'Bulk quantity RFQ',
  'Delivery coordination',
  'Custom profile and accessory guidance',
];

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
export const getCountry = (slug: string) => countries.find((country) => country.slug === slug);
export const getApplication = (slug: string) => applications.find((application) => application.slug === slug);
export const slugifyCategory = (name: string) => categoryInfo.find((category) => category.name === name)?.slug || name.toLowerCase().replaceAll(' ', '-').replaceAll('&', 'and');
